spring.application.name=AutoPlacement
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3310/autoplacement_db
spring.datasource.username=root
spring.datasource.password=WJ28@krhps
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
server.port=8060
#for sending the mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=souravsaha1999@gmail.com
spring.mail.password=ysqx uvpn sech ixcs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
